Remove Warnings that cause errors
/home/heshama/development/cheri/qemu/target-mips/helper.c: In function ‘p2r_addr’:
/home/heshama/development/cheri/qemu/target-mips/helper.c:1049:12: error: variable ‘old_addr’ set
but not used [-Werror=unused-but-set-variable]
     hwaddr old_addr;
                 ^
                 /home/heshama/development/cheri/qemu/target-mips/op_helper.c: In function
                 ‘helper_cbuildcap’:
                 /home/heshama/development/cheri/qemu/target-mips/op_helper.c:2926:31: error:
                 comparison of unsigned expression < 0 is always false [-Werror=type-limits]
                      } else if (ctp->cr_length < 0) {